// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for noti documents
 */
interface NotiDocumentData {
  /**
   * title field in *noti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: noti.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * type field in *noti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: noti.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;

  /**
   * description field in *noti*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: noti.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * link field in *noti*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: noti.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * thumbnail field in *noti*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: noti.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;
}

/**
 * noti document from Prismic
 *
 * - **API ID**: `noti`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NotiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NotiDocumentData>, "noti", Lang>;

export type AllDocumentTypes = NotiDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig,
    ): prismicClient.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type { NotiDocument, NotiDocumentData, AllDocumentTypes };
  }
}
